# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000

runner: "parallel"
batch_size_run: 3
training_iters: 8

entity_last_action: True # Include the user-controlled agents' last actions (one_hot) in their entities

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "flex_qmix"
mixing_embed_dim: 32
hypernet_embed: 128
softmax_mixing_weights: True
agent: "entity_attend_ff"
rnn_hidden_dim: 128
mac: "entity_mac"
attn_embed_dim: 128
attn_n_heads: 4
lmbda: 0.5

name: "coid"


# parameters in coach part
centralized_every: 4
coach_vi: False
copa_influ_loss: True
influ_lambda: 0.001
vi_lambda: 0.0025
entropy_lambda: 0.0001
n_heads: 4
use_coach: True

